### ISSUE TITLE
FileNotFoundError on WIN7/Python3.6.0, installed with Pip

### ISSUE THREAD

**Issue by JaniKarh** [reorx/httpstat#28]
Trying to run `httpstat https://google.com` on Windows 7 with Python 3.6.0, results a stack trace:
```
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\Scripts\httpstat-script.py", line 11, in <module>
    load_entry_point('httpstat==1.2.1', 'console_scripts', 'httpstat')()
  File "c:\users\me\appdata\local\programs\python\python36\lib\site-packages\httpstat.py", line 221, in main
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=cmd_env)
  File "c:\users\me\appdata\local\programs\python\python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "c:\users\me\appdata\local\programs\python\python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by reorx** [comment]
This should be caused by no curl is installed on your machine, because
httpstat must be work with a curl exists on your PATH, you can try install
curl to see if it can fix the problem

**Comment by JaniKarh** [comment]
Did not have curl on my PATH for some reason. Solved, thanks!
